"""Repository rule that generates go_library wrappers for pkg-config deps."""

def _parse_spec(spec):
    parts = spec.split("|", 1)
    if len(parts) != 2:
        fail("invalid go profile spec '{}': expected '<profile>|<lib1,lib2,...>'".format(spec))
    profile = parts[0]
    libs = [lib for lib in parts[1].split(",") if lib]
    return profile, libs

def _go_pkg_config_impl(rctx):
    profile_libs = {}
    all_libs = []

    for spec in rctx.attr.profile_specs:
        profile, libs = _parse_spec(spec)
        if profile in profile_libs:
            fail("duplicate go profile '{}'".format(profile))
        profile_libs[profile] = libs
        for lib in libs:
            if lib not in all_libs:
                all_libs.append(lib)

    build_lines = [
        "# Auto-generated by go_pkg_config repository rule.",
        "# Do not edit.",
        "",
    ]

    # Use aliases in this repo so generated defs.bzl can always refer to local labels.
    for lib in all_libs:
        build_lines.extend([
            "alias(",
            "    name = \"cdep_{}\",".format(lib),
            "    actual = \"@{}//:{}\",".format(lib, lib),
            "    visibility = [\"//visibility:public\"],",
            ")",
            "",
        ])

    build_lines.extend([
        "exports_files([\"defs.bzl\"])",
        "",
    ])

    defs_lines = [
        '"""Auto-generated go_library wrappers for pkg-config cdeps."""',
        "",
        "load(\"@@rules_go+//go:def.bzl\", _go_library = \"go_library\")",
        "",
        "def _go_library_with_cdeps(extra_cdeps, name, cgo = False, cdeps = None, **kwargs):",
        "    merged_cdeps = list(cdeps or [])",
        "    if cgo:",
        "        for dep in extra_cdeps:",
        "            if dep not in merged_cdeps:",
        "                merged_cdeps.append(dep)",
        "    _go_library(name = name, cgo = cgo, cdeps = merged_cdeps, **kwargs)",
        "",
    ]

    for profile in sorted(profile_libs.keys()):
        cdeps = ["Label(\"//:cdep_{}\")".format(lib) for lib in profile_libs[profile]]
        defs_lines.extend([
            "def go_library_{}(name, **kwargs):".format(profile),
            "    _go_library_with_cdeps([{}], name, **kwargs)".format(", ".join(cdeps)),
            "",
        ])

    rctx.file("BUILD.bazel", "\n".join(build_lines))
    rctx.file("defs.bzl", "\n".join(defs_lines))

go_pkg_config = repository_rule(
    implementation = _go_pkg_config_impl,
    attrs = {
        "profile_specs": attr.string_list(
            mandatory = True,
            doc = "List of '<profile>|<lib1,lib2,...>' specs.",
        ),
    },
    local = True,
    doc = "Generates go_library wrapper macros backed by pkg-config cdeps.",
)
